import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useContext, useEffect, createContext } from 'react'
import { SomeContext } from './_app'

export const getServerSideProps = async () => {
  return { props: { changeContext: 52 } };
};

export default function Home() {
  const { contextValue, setContextValue } = useContext(SomeContext);
  console.log("🚀 ~ file: index.js:12 ~ About ~ contextValue:", contextValue)

  // NOTE: Pac content du set()
  // setContextValue(5)
  // console.log("🚀 ~ file: index.js:14 ~ Home ~ contextValue:", contextValue)

  // useEffect(() => {
  //   setContextValue(contextValue + 1)
  //   console.log("🚀 ~ file: index.js:14 ~ Home ~ contextValue:", contextValue)
  // }, [contextValue]);

  return (
    <>
      <Head>
        <title>About Us: Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.main}`}>
            <SomeContext.Provider value={contextValue + 1}>
                <h1>About: {contextValue + 1}</h1>
            </SomeContext.Provider>

            <h1>About: {contextValue}</h1>
      </div>
    </>
  )
}
